### ISSUE TITLE
Question: Private Repo, Github App Callback URL

### ISSUE THREAD

**Issue by mikerkeating** [petebacondarwin/github-pr-helper#16]
Hi @petebacondarwin 

Thanks for this work; I think it's a really useful feature. 

All works well in a public repo but it's not working for me in a private repo. Hopefully you can help
- I installed the plugin from [the Chrome web store](https://chrome.google.com/webstore/detail/github-pr-helper/mokbklfnaddkkbolfldepnkfmanfhpen/related) 
- In a private repo on a pull request page, I can see the label control but no labels. 
- If I don't register an app; the github api call to get labels fails. Registering an app with fake callback url throws missing callback errors. 

Does the project work for private repos? Is the callback url necessary and what needs to be at that callback url? 

Thanks, Mike

**Comment by petebacondarwin** [comment]
Hi @mikerkeating - thanks for trying out this tool and providing feedback.
You are right, there seems to be a problem with private repositories.  From a quick play, I think that the issue is that the client_id/client_secret authentication isn't enough to access the private repository or possibly that the requests to the API need to be different when the repository is private.

I'll look into it.

**Comment by petebacondarwin** [comment]
OK, it does appear that client_id/client_secret style of authentication does not work for private repositories.
The good news is that I spiked using a "personal access token" and this does seem to work across the board.  So I'll fix this up and get a new version out.

**Comment by petebacondarwin** [comment]
Personal Token support added at 0.2.0 - see 68b67de19a68dc3bad53db532e8ab416d8afc83d. You can get it now on the Chrome Web Store.

No more application key generation required AND it works with private repositories.

**Comment by mikerkeating** [comment]
Brilliant; thanks for the fix and fast response @petebacondarwin!
